return {
  'folke/which-key.nvim',
  event = 'VeryLazy',
  opts = {
    delay = 0,
    preset = 'modern',
    spec = {
      { '<leader>b', group = '[B]uffer' },
      { '<leader>c', group = '[C]ode' },
      { '<leader>d', group = '[D]ebug' },
      { '<leader>g', group = '[G]it' },
      { '<leader>l', group = '[L]SP' },
      { '<leader>m', group = '[M]arkdown' },
      { '<leader>r', group = '[R]un' },
      { '<leader>s', group = '[S]earch' },
      { '<leader>w', group = '[W]orkspace' },
      { '<leader>t', group = '[T]oggle' },
      { 'g', group = '[G]oto' },
      { '[', group = 'Previous' },
      { ']', group = 'Next' },
      -- Panel toggles
      { '<M-1>', desc = 'Neo-tree Explorer', icon = '󰙅' },
      { '<M-2>', desc = 'Neo-tree Buffers', icon = '󰓩' },
      { '<M-t>', desc = 'Terminal', icon = '' },
      { '<M-9>', desc = 'Neotest summary', icon = '󰙅' },
      { '<M-8>', desc = 'Run overview (Overseer)', icon = '󰑮' },
      { '<M-7>', desc = 'DAP view', icon = '' },
      { '<M-u>', desc = 'Undo tree', icon = '󰕌' },
      { '<M-x>', desc = 'Diagnostics (Trouble)', icon = '󱖫' },
      { '<M-o>', desc = 'Document symbols (Trouble)', icon = '󰆧' },
      { '<M-q>', desc = 'Quickfix (Trouble)', icon = '󰁨' },
    },
  },
}
