return {
  'folke/which-key.nvim',
  event = 'VimEnter',
  opts = {
    delay = 0,
    preset = 'modern',
    spec = {
      { '<leader>b', group = '[B]uffer' },
      { '<leader>c', group = '[C]ode' },
      { '<leader>d', group = '[D]ebug' },
      { '<leader>g', group = '[G]it' },
      { '<leader>l', group = '[L]SP' },
      { '<leader>m', group = '[M]arkdown' },
      { '<leader>r', group = '[R]un' },
      { '<leader>s', group = '[S]earch' },
      { '<leader>w', group = '[W]orkspace' },
      { '<leader>t', group = '[T]oggle' },
      { 'g', group = '[G]oto' },
      { '[', group = 'Previous' },
      { ']', group = 'Next' },
      -- Panel toggles
      { '<M-e>', desc = 'Neo-tree [E]xplorer', icon = '󰙅' },
      { '<M-b>', desc = 'Neo-tree [B]uffers', icon = '󰓩' },
      { '<M-t>', desc = '[T]erminal', icon = '' },
      { '<M-r>', desc = '[R]un overview (Overseer)', icon = '󰑮' },
      { '<M-d>', desc = '[D]AP view', icon = '' },
      { '<M-u>', desc = '[U]ndo tree', icon = '󰕌' },
      { '<M-x>', desc = 'Diagnostics (Trouble)', icon = '󱖫' },
      { '<M-o>', desc = 'Document symbols (Trouble)', icon = '󰆧' },
      { '<M-q>', desc = '[Q]uickfix (Trouble)', icon = '󰁨' },
    },
  },
}
