vim.g.have_nerd_font = true
vim.opt.relativenumber = true
vim.opt.number = true
vim.opt.mouse = 'a' -- Enable mouse mode, can be useful for resizing splits for example!
vim.opt.showmode = false -- Don't show the mode, since it's already in the status line
vim.opt.clipboard:append 'unnamedplus' -- Use the system clipboard as default register
vim.opt.breakindent = true -- Enable break indent
vim.opt.undofile = true -- Save undo history
vim.opt.ignorecase = true -- Case-insensitive searching UNLESS \C or one or more capital letters in the search term
vim.opt.smartcase = true -- Case-sensitive searching when the search pattern contains uppercase letters
vim.opt.signcolumn = 'yes' -- Keep signcolumn on by default
vim.opt.updatetime = 250 -- Decrease update time
vim.opt.timeoutlen = 300 -- Decrease mapped sequence wait time
vim.opt.splitright = true -- Vertical splits will automatically be to the right of the current window
vim.opt.splitbelow = true -- Horizontal splits will automatically be below the current window
vim.opt.list = true -- Show some invisible characters (tabs..., trailing spaces...)
vim.opt.listchars = { tab = '» ', trail = '·', nbsp = '␣' }
vim.opt.inccommand = 'split' -- Preview substitutions live, as you type!
vim.opt.cursorline = true -- Show which line your cursor is on
vim.opt.scrolloff = 10 -- Minimal number of screen lines to keep above and below the cursor.
vim.opt.hlsearch = true -- Set highlight on search, but clear on pressing <Esc> in normal mode
vim.opt.encoding = 'utf-8'
vim.opt.spelllang = { 'en', 'de' }
vim.opt.spelloptions = 'camel'
vim.opt.spell = true
vim.opt.wildmenu = true -- tab completion
vim.opt.wildmode = { 'longest:full', 'full' } -- Command-line completion mode
vim.opt.termguicolors = true
vim.o.sessionoptions = 'blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions'
vim.opt.shiftround = true -- Round indent to multiple of 'shiftwidth'
vim.opt.shiftwidth = 4
vim.opt.tabstop = 4
vim.opt.expandtab = true
vim.opt.completeopt = 'menu,menuone,noselect,popup'
vim.opt.laststatus = 3 -- global statusline
vim.opt.synmaxcol = 300 -- syntax highlighting limit
vim.opt.backup = false -- do not create a backup file
vim.opt.writebackup = false -- do not write to a backup file
vim.opt.swapfile = false -- do not create a swapfile
vim.opt.autoread = true -- auto-reload changes if outside of neovim
vim.opt.autowrite = false -- do not auto-save
vim.opt.backspace = 'indent,eol,start' -- better backspace behaviour
vim.opt.diffopt:append 'linematch:60' -- improve diff display
vim.opt.redrawtime = 10000 -- increase neovim redraw tolerance
vim.opt.maxmempattern = 20000 -- increase max memory
